In [2]:
import numpy as np

In [14]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
print(X)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [13]:
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

print(syn0)
print(syn1)

[[-0.86367564 -0.26151471 -0.35569675 -0.25775833]
 [ 0.45338576  0.74565369  0.15414348 -0.84472889]
 [ 0.37239939  0.30833292  0.42900626  0.8009333 ]]
[[ 0.3220636 ]
 [ 0.63199502]
 [-0.18679595]
 [ 0.31323408]]


In [15]:
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)